# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3019c1b83843cf836505f8884baf76fc4b6967a0f38b8298daad69b9595bde13b9967393a05cc27063a661c40672e647c03b3ef0cf3849f061cd2cd552af9632

test:
  secret_key_base: 65415d9efc34f0fb4847b08b0843c4ae40d332df4e532b8614785e17bb3aed7ba836fdf38259b388a30e93b1141c55361013d487b705bcf8b5b07bc3682c6d1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
